### ISSUE TITLE
hang

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/reduce#3]
Doing an ARCH=arm build, I suspect the interactive kconfig prompt is coming up.

Perhaps I need to manually set `ARCH=arm` in the env before running reduce.py?

```
/android2/reduce/reduce.py prep drivers/gpu/drm/amd/amdgpu/../display/dc/dml/calcs/dce_calcs   
[INFO] Using CC=clang
[INFO] Making drivers/gpu/drm/amd/amdgpu/../display/dc/dml/calcs/dce_calcs.i...
^CTraceback (most recent call last):
  File "/android2/reduce/reduce.py", line 62, in <module>
    args.func(args)
  File "/android2/reduce/src/prep.py", line 339, in main
    path_to_dot_i_file, make_stdout = make_dot_i_file(
                                      ^^^^^^^^^^^^^^^^
  File "/android2/reduce/src/prep.py", line 60, in make_dot_i_file
    make_output = subprocess.run(
                  ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 2108, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

**Comment by nathanchance** [comment]
> Perhaps I need to manually set `ARCH=arm` in the env before running reduce.py?

That may work, although I think the real solution is either using the existing `build_command` customization to supply something like `make -j$(nproc) ARCH=arm LLVM=1 V=1` or refactoring `build_command` to allow specifying or modifying the variables, rather than the whole command.

**Comment by nickdesaulniers** [comment]
So this works:

`ARCH=riscv /android2/reduce/reduce.py prep net/netlink/af_netlink.i`

Perhaps we can detect+warn if the arch doesn't match the arch in the .config?

**Comment by nathanchance** [comment]
If we have the configuration, we could just set `ARCH` automatically?
